### ISSUE TITLE
Faltan algunas imagenes...

### ISSUE THREAD

**Issue by baltazarAvave** [gpaez/AndroidISII#1]
Hola @gpaez parece que faltan algunas imagenes en tu carpeta drawable,
estoy teniendo estos errores al compilar lo que descargué
`C:\home\TareasAndroid\G15\AndroidISII-master\Gestor_Ventas\src\main\res\layout\home.xml
Error:(6, 37) No resource found that matches the given name (at 'background' with value '@drawable/bg3').

C:\home\TareasAndroid\G15\AndroidISII-master\Gestor_Ventas\build\intermediates\res\merged\debug\layout\ac_sign_in.xml
Error:(65, 22) No resource found that matches the given name (at 'src' with value '@drawable/logo').`
podrías indicarme donde las encuentro?

**Comment by gpaez** [comment]
Acabo se subir las imágenes, no se habían agregado, por eso no se subieron al git

**Comment by baltazarAvave** [comment]
@gpaez me podrías levantar la última versión de la apk, por favor? no estoy pudiendo levantar la app en el emulador...

**Comment by baltazarAvave** [comment]
esta correcto
